### ISSUE TITLE
incorrect memory request values

### ISSUE THREAD

**Issue by bcha** [FairwindsOps/goldilocks#208]
We're having issues with incorrect current memory request values with Goldilocks. It sure _seems_ it's just replicating the Memory Limit value for some reason. Every other value is correct across all apps.

For instance:
![image](https://user-images.githubusercontent.com/13367879/91039547-6ca9f200-e615-11ea-9db6-1f7d50fed247.png)

Yet when I check what they actually are with kubectl:
  ```
Limits:
    cpu:     2
    memory:  1Gi
Requests:
    cpu:      50m
    memory:   780Mi
```

I checked this on multiple apps and it seems that this is happening with all our deployments across multiple different clusters.

Goldilocks seems to be running just fine, restarting it didn't help and it logs nothing that indicates that anything is wrong. We're running the latest release.

**Comment by sudermanjr** [comment]
I think this may be fixed in master. I'm trying to find the PR that fixed it. 

Can you try using the image tag `build_1920` and see if it is fixed?

**Comment by oskapt** [comment]
I just upgraded to build_1920 in Helm and the dashboard is broken:

<img width="993" alt="Screen Shot 2020-08-25 at 21 44 34" src="https://user-images.githubusercontent.com/171292/91245786-5044ad00-e71c-11ea-9681-f572be6a8bd1.png">

Furthermore, `build_1920` returns a 301 permanent redirect from `/` to `/namespaces`, so reverting to the previous version means the old dashboard is no longer visible and the redirect to `/namespaces` 404s. Users will have to to drop the browser cache to get the old dashboard to load.

```
➤ curl -I localhost:8080
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Location: /namespaces
Date: Wed, 26 Aug 2020 01:57:50 GMT
```

I think for something like this, where it's not public-facing, a 302 is better.

**Comment by oskapt** [comment]
This actually looks like an RBAC issue:
```
E0826 02:04:48.988482       1 namespace-list.go:22] Error getting namespace list: namespaces is forbidden: User  │
│ stream closed
```

**Comment by sudermanjr** [comment]
Thanks, I actually realized that myself and opened a PR on the chart https://github.com/FairwindsOps/charts/pull/351

I'll get that merged today

**Comment by sudermanjr** [comment]
Chart 2.3.5 with build_1920 should do the trick.  I'll work on getting releases out this week hopefully so that this is fixed permanently

**Comment by oskapt** [comment]
Thanks for fixing the namespace issue. I upgraded to 2.3.5 with build_1920, and it still shows the same value for request and limit.

<img width="921" alt="Screen Shot 2020-08-26 at 14 23 56" src="https://user-images.githubusercontent.com/171292/91341739-f7baf180-e7a7-11ea-837b-77d2e7200172.png">

These are the actual values on the workload:

```
        resources:
          limits:
            memory: 450Mi
          requests:
            memory: 300Mi
```

**Comment by sudermanjr** [comment]
Thanks for checking. I'll take a look

**Comment by sudermanjr** [comment]
This should be fixed in `build_2049`.

**Comment by oskapt** [comment]
Hello...build_2049 introduces this new error message when clicking "View" for a namespace. 

<img width="672" alt="Screen Shot 2020-09-03 at 09 48 35" src="https://user-images.githubusercontent.com/171292/92123501-bb504c80-edca-11ea-8c98-d639538b8d0a.png">

**Comment by Art3mK** [comment]
2049 doesn't work for me either, I've installed chart 2.3.5
in controller logs:
```
I0907 12:12:16.635119       1 controller.go:119] Starting controller.
I0907 12:12:16.635190       1 controller.go:122] Creating watcher for Deployments.
I0907 12:12:16.635223       1 controller.go:170] Creating controller for resource type deployment
I0907 12:12:16.635259       1 controller.go:142] Creating watcher for Namespaces.
I0907 12:12:16.635267       1 controller.go:170] Creating controller for resource type namespace
I0907 12:12:16.635318       1 controller.go:49] Starting watcher.
I0907 12:12:16.635382       1 controller.go:49] Starting watcher.
I0907 12:12:16.635485       1 reflector.go:175] Starting reflector *v1.Namespace (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I0907 12:12:16.635658       1 reflector.go:175] Starting reflector *v1.Deployment (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I0907 12:12:16.936510       1 controller.go:185] namespace/example added.
I0907 12:12:16.936532       1 controller.go:185] namespace/example added.
I0907 12:12:16.936691       1 controller.go:185] namespace/example added.
I0907 12:12:16.936706       1 controller.go:185] namespace/example added.
I0907 12:12:16.936720       1 controller.go:185] namespace/example added.
...
I0907 12:12:17.134227       1 controller.go:61] Watcher synced.
I0907 12:12:17.234233       1 namespace.go:35] Namespace example updated. Check the labels.
E0907 12:12:17.334444       1 vpa.go:77] the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
E0907 12:12:17.536901       1 namespace.go:38] Error reconciling: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
I0907 12:12:17.536935       1 namespace.go:35] Namespace example updated. Check the labels.
E0907 12:12:17.634317       1 vpa.go:77] the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
...
E0907 12:12:17.934375       1 vpa.go:77] the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
E0907 12:12:17.934396       1 namespace.go:38] Error reconciling: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
I0907 12:12:17.934411       1 namespace.go:35] Namespace example updated. Check the labels.
I0907 12:12:18.235412       1 controller.go:185] deployment/example has been added.
I0907 12:12:18.235434       1 controller.go:185] deployment/example has been added.
...
I0907 12:12:18.235612       1 controller.go:61] Watcher synced.
E0907 12:12:18.236201       1 vpa.go:77] the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
E0907 12:12:18.236207       1 namespace.go:38] Error reconciling: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
I0907 12:12:18.236224       1 namespace.go:35] Namespace example updated. Check the labels.
E0907 12:12:18.348450       1 vpa.go:77] the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
E0907 12:12:18.348470       1 deployment.go:47] Error reconciling: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
E0907 12:12:18.349149       1 vpa.go:77] the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
...
```
dashboard initially shows only 2 namespaces for some reason (the same happens with build_1920).

links in dash doesn't work, shows only `Error running summary` with this line logged
```
goldilocks-dashboard-5bf9b76c55-q7pmj goldilocks E0907 12:24:35.739609       1 summary.go:207] the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
goldilocks-dashboard-5bf9b76c55-q7pmj goldilocks E0907 12:24:35.739624       1 dashboard.go:45] Error getting vpaData: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
```

build_1920 works somehow, at least it could get VPAs and shows values for them. Dash still shows only 2 namespaces initially for some reason

**Comment by Art3mK** [comment]
ping @sudermanjr, should this issue be reopened?

**Comment by sudermanjr** [comment]
This feels like a different issue, but I will be taking a pass at Goldilocks this week in order to get a 3.0 release out, so I will catch this in that.

**Comment by sudermanjr** [comment]
@Art3mK and @oskapt

I've been looking at this today. It seems like the update to the newer version of the vertical pod autoscaler CRD has introduced these issues. The chart has not yet taken this into consideration. Essentially, the best route to use the current unreleased version is to remove the vpa installation from goldilocks and to install directly from master on the autoscaling repository.

I will be working this week to clean up this workflow and make an upgrade path to the newer VPA versions cleaner, as well as a clean release of Goldilocks to go with it. Keep an eye out for v3.0 of the chart and Goldilocks that should take care of these issues.

Thanks for you patience as we make all these really big changes to Goldilocks!

**Comment by bcha** [comment]
ping @sudermanjr 

The issues that @Art3mK & @oskapt described still persist in v3.0.0. Recap:
- Dashboard still redirects to /namespaces
- Only shows a couple of namespaces for some reason
- `Error running summary` with links
- Keeps throwing `the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)`

Should new tickets to opened for these? Any ETA on the VPA issue?

**Comment by sudermanjr** [comment]
Can you please file a new issue for the issues you are having, preferably with the following information:

1) Install method of Goldilocks
2) Install method of VPA
3) Version of VPA
4) Version of any helm charts used
5) A detailed explanation of how to reproduce

This thread has gotten far too bloated and has too many issues to triage and diagnose in it.
